package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/oryx-systems/makao/pkg/makao/application/dto"
	"github.com/oryx-systems/makao/pkg/makao/domain"
)

// CreateResidence is the resolver for the createResidence field.
func (r *mutationResolver) CreateResidence(ctx context.Context, input dto.ResidenceInput) (*domain.Residence, error) {
	r.checkPreconditions()

	return r.makao.Residence.CreateResidence(ctx, input)
}
