package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/oryx-systems/makao/pkg/makao/domain"
	"github.com/oryx-systems/makao/pkg/makao/presentation/graph/generated"
)

// GetUserResidences is the resolver for the getUserResidences field.
func (r *queryResolver) GetUserResidences(ctx context.Context) ([]*domain.Residence, error) {
	r.checkPreconditions()

	return r.makao.User.GetUserResidences(ctx)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
